import re
import json
# pyrefly: ignore [missing-import]
import joblib
import warnings
# pyrefly: ignore [missing-import]
import numpy as np
import pandas as pd

from bs4 import BeautifulSoup
# pyrefly: ignore [missing-import]
from scipy.sparse import hstack

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

from armis_email_preprocessing import clean_email_body

from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    precision_score,
    recall_score,
    f1_score
)

warnings.filterwarnings("ignore")

# =========================================================
# CONFIG
# =========================================================

JSON_PATH = r"armis_raw_email.json"

LABELED_CSV_PATH = r"labeled_emails.csv"

FILTERED_OUTPUT_PATH = r"filtered_bulk_emails.json"

GENUINE_OUTPUT_PATH = r"genuine_emails.csv"

MODEL_PATH = r"email_filter_model.pkl"

VECTORIZER_PATH = r"tfidf_vectorizer.pkl"

THRESHOLD = 0.95


# =========================================================
# LOAD DATA
# =========================================================

def load_json_dataset(filepath):

    with open(filepath, "r", encoding="utf-8") as f:
        data = json.load(f)

    emails = []

    for email_id, text in data.items():

        emails.append({
            "email_id": email_id,
            "text": str(text)
        })

    return pd.DataFrame(emails)


# =========================================================
# ADVANCED CLEANING
# =========================================================

def clean_email_text(text):
    text = str(text)

    # -----------------------------------------------------
    # Robust Preprocessing Pipeline
    # -----------------------------------------------------
    text = clean_email_body(text, keep_history=False)

    # -----------------------------------------------------
    # Downstream Normalization for ML Features
    # -----------------------------------------------------
    text = text.lower()

    # Replace URLs and emails with standard tokens used by TF-IDF & extract_extra_features
    text = re.sub(r"http\S+", " url ", text)
    text = re.sub(r"\S+@\S+", " email ", text)

    # Remove Repeated Underscores
    text = re.sub(r"_+", " ", text)

    # Remove Excessive Spaces
    text = re.sub(r"\s+", " ", text).strip()

    return text


# =========================================================
# WEAK LABELING
# =========================================================

AUTOMATED_PATTERNS = {

    "ooo": [
        "out of office",
        "out-of-office",
        "automatic reply",
        "autoreply",
        "i am currently out of the office",
        "i will respond upon my return",
        "limited access during this time",
        "replies delayed"
    ],

    "newsletter": [
        "unsubscribe",
        "manage preferences",
        "newsletter",
        "digest",
        "view in browser"
    ],

    "system": [
        "automated message",
        "do not reply",
        "delivery failure",
        "undeliverable",
        "mailer-daemon",
        "generated automatically"
    ],

    "ai_generated": [
        "generated by ai",
        "meeting notes"
    ]
}


def weak_label(text):

    text = text.lower()

    for category, patterns in AUTOMATED_PATTERNS.items():

        for pattern in patterns:

            if pattern in text:
                return 1, category

    return 0, "genuine"


# =========================================================
# CREATE LABELING DATASET
# =========================================================

def create_labeling_dataset(df):

    labels = []
    categories = []

    for text in df["text"]:

        label, category = weak_label(text)

        labels.append(label)
        categories.append(category)

    df["label"] = labels
    df["category"] = categories

    return df


# =========================================================
# FEATURE ENGINEERING
# =========================================================

def extract_extra_features(df):

    features = pd.DataFrame()

    text = df["clean_text"]

    # -----------------------------------------------------
    # Automation Indicators
    # -----------------------------------------------------

    features["contains_unsubscribe"] = (
        text.str.contains("unsubscribe")
    ).astype(int)

    features["contains_ooo"] = (
        text.str.contains("out of office")
    ).astype(int)

    features["contains_do_not_reply"] = (
        text.str.contains("do not reply")
    ).astype(int)

    features["contains_generated_by_ai"] = (
        text.str.contains("generated by ai")
    ).astype(int)

    features["contains_meeting_notes"] = (
        text.str.contains("meeting notes")
    ).astype(int)

    # -----------------------------------------------------
    # Structural Features
    # -----------------------------------------------------

    features["text_length"] = text.str.len()

    features["num_urls"] = text.str.count("url")

    features["num_reply_markers"] = text.str.count("reply")

    return features


# =========================================================
# TRAIN MODEL
# =========================================================

def train_model(df):

    print("\n========== TRAINING MODEL ==========")

    # -----------------------------------------------------
    # Clean Text
    # -----------------------------------------------------

    df["clean_text"] = df["text"].apply(clean_email_text)

    # -----------------------------------------------------
    # TF-IDF
    # -----------------------------------------------------

    vectorizer = TfidfVectorizer(
        max_features=15000,
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95,
        stop_words="english",
        sublinear_tf=True
    )

    X_text = vectorizer.fit_transform(df["clean_text"])

    # -----------------------------------------------------
    # Extra Features
    # -----------------------------------------------------

    X_extra = extract_extra_features(df)

    # -----------------------------------------------------
    # Combine Features
    # -----------------------------------------------------

    X = hstack([X_text, X_extra.values])

    y = df["label"]

    # -----------------------------------------------------
    # Train/Test Split
    # -----------------------------------------------------

    X_train, X_test, y_train, y_test = train_test_split(
        X,
        y,
        test_size=0.2,
        random_state=42,
        stratify=y
    )

    # -----------------------------------------------------
    # Logistic Regression
    # -----------------------------------------------------

    model = LogisticRegression(
        max_iter=3000,
        class_weight="balanced"
    )

    model.fit(X_train, y_train)

    # -----------------------------------------------------
    # Evaluation
    # -----------------------------------------------------

    y_pred = model.predict(X_test)

    print("\n========== EVALUATION ==========")

    print(classification_report(
        y_test,
        y_pred,
        target_names=[
            "Genuine",
            "Automated"
        ]
    ))

    cm = confusion_matrix(y_test, y_pred)

    print("\nConfusion Matrix:")
    print(cm)

    # -----------------------------------------------------
    # Critical Metric
    # -----------------------------------------------------

    false_positive_for_automated = cm[0][1]

    print(
        f"\nGenuine emails wrongly filtered: "
        f"{false_positive_for_automated}"
    )

    # -----------------------------------------------------
    # Save
    # -----------------------------------------------------

    joblib.dump(model, MODEL_PATH)
    joblib.dump(vectorizer, VECTORIZER_PATH)

    print("\n========== MODEL SAVED ==========")

    return model, vectorizer


# =========================================================
# INFERENCE
# =========================================================

def classify_emails(df, model, vectorizer):

    print("\n========== RUNNING FILTER ==========")

    df["clean_text"] = df["text"].apply(clean_email_text)

    # -----------------------------------------------------
    # TF-IDF
    # -----------------------------------------------------

    X_text = vectorizer.transform(df["clean_text"])

    # -----------------------------------------------------
    # Extra Features
    # -----------------------------------------------------

    X_extra = extract_extra_features(df)

    # -----------------------------------------------------
    # Combine
    # -----------------------------------------------------

    X = hstack([X_text, X_extra.values])

    # -----------------------------------------------------
    # Probabilities
    # -----------------------------------------------------

    probabilities = model.predict_proba(X)[:, 1]

    # -----------------------------------------------------
    # Weak Heuristics
    # -----------------------------------------------------

    heuristic_preds = []

    for text in df["clean_text"]:

        pred, _ = weak_label(text)

        heuristic_preds.append(pred)

    heuristic_preds = np.array(heuristic_preds)

    # -----------------------------------------------------
    # Conservative Logic
    # -----------------------------------------------------

    final_preds = []

    for heuristic_pred, prob in zip(
        heuristic_preds,
        probabilities
    ):

        # Strong heuristic
        if heuristic_pred == 1:
            final_preds.append(1)

        # High-confidence ML
        elif prob >= THRESHOLD:
            final_preds.append(1)

        # Otherwise KEEP email
        else:
            final_preds.append(0)

    df["automation_probability"] = probabilities
    df["is_filtered"] = final_preds

    return df


# =========================================================
# SAVE RESULTS
# =========================================================

# =========================================================
# SAVE RESULTS
# =========================================================

def save_outputs(df):

    # -----------------------------------------------------
    # Split Data
    # -----------------------------------------------------

    genuine_df = df[df["is_filtered"] == 0]

    filtered_df = df[df["is_filtered"] == 1]

    # -----------------------------------------------------
    # FILE PATHS
    # -----------------------------------------------------

    GENUINE_EMAILS_CSV = (
        r"C:\Users\purni\Desktop\Armis_Email\genuine_emails.csv"
    )

    FILTERED_EMAILS_JSON = (
        r"C:\Users\purni\Desktop\Armis_Email\filtered_emails.json"
    )

    GENUINE_BODIES_TXT = (
        r"C:\Users\purni\Desktop\Armis_Email\genuine_email_bodies.txt"
    )

    FILTERED_BODIES_TXT = (
        r"C:\Users\purni\Desktop\Armis_Email\filtered_email_bodies.txt"
    )

    # Ensure output directory exists
    import os
    os.makedirs(r"C:\Users\purni\Desktop\Armis_Email", exist_ok=True)

    # -----------------------------------------------------
    # 1. SAVE GENUINE EMAILS
    # -----------------------------------------------------

    genuine_df_export = genuine_df.copy()
    if "text" in genuine_df_export.columns:
        genuine_df_export["text"] = genuine_df_export["text"].astype(str).str.replace(r"[\r\n]+", " ", regex=True)
    if "clean_text" in genuine_df_export.columns:
        genuine_df_export["clean_text"] = genuine_df_export["clean_text"].astype(str).str.replace(r"[\r\n]+", " ", regex=True)

    genuine_df_export.to_csv(
        GENUINE_EMAILS_CSV,
        index=False,
        encoding="utf-8-sig"
    )

    # -----------------------------------------------------
    # 2. SAVE FILTERED EMAILS
    # -----------------------------------------------------

    filtered_df.to_json(
        FILTERED_EMAILS_JSON,
        orient="records",
        indent=4
    )

    # -----------------------------------------------------
    # 3. SAVE GENUINE EMAIL BODIES
    # -----------------------------------------------------

    with open(
        GENUINE_BODIES_TXT,
        "w",
        encoding="utf-8"
    ) as f:

        for _, row in genuine_df.iterrows():

            f.write("=" * 80 + "\n")
            f.write(f"EMAIL ID: {row['email_id']}\n")
            f.write("=" * 80 + "\n\n")

            f.write(str(row["text"]))
            f.write("\n\n\n")

    # -----------------------------------------------------
    # 4. SAVE FILTERED EMAIL BODIES
    # -----------------------------------------------------

    with open(
        FILTERED_BODIES_TXT,
        "w",
        encoding="utf-8"
    ) as f:

        for _, row in filtered_df.iterrows():

            f.write("=" * 80 + "\n")
            f.write(f"EMAIL ID: {row['email_id']}\n")
            f.write("=" * 80 + "\n\n")

            f.write(str(row["text"]))
            f.write("\n\n\n")

    # -----------------------------------------------------
    # STATS
    # -----------------------------------------------------

    print("\n========== RESULTS ==========")

    print(f"Genuine emails kept: {len(genuine_df)}")
    print(f"Automated emails filtered: {len(filtered_df)}")

    print("\n========== SAVED FILES ==========")

    print(f"\n1. Genuine Emails CSV:")
    print(GENUINE_EMAILS_CSV)

    print(f"\n2. Filtered Emails JSON:")
    print(FILTERED_EMAILS_JSON)

    print(f"\n3. Genuine Email Bodies TXT:")
    print(GENUINE_BODIES_TXT)

    print(f"\n4. Filtered Email Bodies TXT:")
    print(FILTERED_BODIES_TXT)

# =========================================================
# MAIN
# =========================================================

def main():

    print("\n========== LOADING DATA ==========")

    df = load_json_dataset(JSON_PATH)

    print(f"Loaded emails: {len(df)}")

    # -----------------------------------------------------
    # Create Labels
    # -----------------------------------------------------

    df_labeled = create_labeling_dataset(df.copy())

    # -----------------------------------------------------
    # Save Labeling CSV
    # -----------------------------------------------------

    df_labeled.to_csv(
        LABELED_CSV_PATH,
        index=False
    )

    print("\nSaved labeling dataset:")
    print(LABELED_CSV_PATH)

    # -----------------------------------------------------
    # Train
    # -----------------------------------------------------

    model, vectorizer = train_model(df_labeled)

    # -----------------------------------------------------
    # Inference
    # -----------------------------------------------------

    df_final = classify_emails(
        df,
        model,
        vectorizer
    )

    # -----------------------------------------------------
    # Save Results
    # -----------------------------------------------------

    save_outputs(df_final)

    print("\n========== PIPELINE COMPLETE ==========")


# =========================================================
# RUN
# =========================================================

if __name__ == "__main__":
    main()